// DWP-ANGULAR/src/app/playground/playground.component.ts
import { Component, OnInit } from '@angular/core';
import { Subject, Subscription } from 'rxjs';
import { debounceTime, distinctUntilChanged } from 'rxjs/operators';
import { ConfigService as ApiService } from '../services/config.service';
import { IUsers } from './playgorund.model';

@Component({
  selector: 'app-playground',
  templateUrl: './playground.component.html',
  styleUrls: ['./playground.component.scss'],
})
export class PlaygroundComponent implements OnInit {
  allUsers: IUsers[];
  userQuery: string;
  fetchAllUsers_BKUP: IUsers[];
  locationAround: IUsers[];
  userID: number;
  defaultCityName = 'London';
  cityLatitude: number = 51.50722;
  cityLongitude: number = -0.1275;

  $userQuery: Subject<string> = new Subject<string>();

  private cityNameChangedSubscription: Subscription;

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.cityNameChangedSubscription = this.$userQuery
      .pipe(debounceTime(1500), distinctUntilChanged())
      .subscribe((newCityName) => {
        this.userQuery = newCityName;
        if (newCityName.length > 1 || +newCityName > 1) {
          if (!isNaN(+newCityName)) {
            this.calculateDistance();
          } else {
            this.resolveQueryBasedOnCity(this.userQuery);
          }
        } else {
          this.allUsers = this.fetchAllUsers_BKUP;
        }
      });

    this.getAllUsers();
  }

  /**
   * Makes a GET request to USERS API and retrives all users.
   *
   * @memberof PlaygroundComponent
   */
  getAllUsers(): void {
    this.apiService.fetchUsersList().subscribe((users) => {
      this.allUsers = users;
      this.fetchAllUsers_BKUP = users;
    });
  }

  /**
   * Makes a GET request using userID to get user Details
   *
   * @param {number} [id]
   * @memberof PlaygroundComponent
   */
  getUserDetails(id?: number) {
    this.apiService.getUserDetailsByID(id).subscribe((user) => {
      this.allUsers = [user];
    });
  }

  /**
   * This calculates the distance between two points (given the latitude/longitude of those points).
   * Reference: https://www.geodatasource.com/developers/javascript
   *
   * @param {number} eachLatitude
   * @param {number} eachLongitude
   * @param {number} cityLatitude
   * @param {number} cityLongitude
   *
   * @param {string} [unit]
   * @return {*}  {number}
   */
  public getNearCityUsers(
    eachLatitude: number,
    eachLongitude: number,
    cityLatitude: number,
    cityLongitude: number,
    unit?: string
  ): number {
    if (eachLatitude == cityLatitude && eachLongitude == cityLongitude) {
      return 0;
    } else {
      var radlat1 = (Math.PI * eachLatitude) / 180;
      var radlat2 = (Math.PI * cityLatitude) / 180;
      var theta = eachLongitude - cityLongitude;
      var radtheta = (Math.PI * theta) / 180;
      var distance =
        Math.sin(radlat1) * Math.sin(radlat2) +
        Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);

      if (distance > 1) distance = 1;

      distance = Math.acos(distance);
      distance = (distance * 180) / Math.PI;
      distance = distance * 60 * 1.1515;

      if (unit == 'K') {
        distance = distance * 1.609344;
      }
      if (unit == 'N') {
        distance = distance * 0.8684;
      }

      return distance;
    }
  }

  /**
   * Helps user to see all users details.
   *
   * @public
   */
  initialState(): void {
    this.userQuery = undefined;
    this.userID = undefined;
    
    this.allUsers = this.fetchAllUsers_BKUP;
  }

  /**
   * Makes GET request with userQuery to retrives the users that belongs to.
   * userQuery => It takes either string(Location) or number(Miles).
   *
   * @private
   * @param {string} userQuery
   */
  private resolveQueryBasedOnCity(userQuery: string): void {
    this.apiService.resolveQuery(userQuery).subscribe((selectedCityUsers) => {
      this.allUsers = selectedCityUsers;
    });
  }

  /**
   * Method which calculates the distance from static point to all users location.
   * @result will be saved in "locationAround"
   *
   * @private
   */
  private calculateDistance(): void {
    let distance: number;
    this.locationAround = [];

    this.fetchAllUsers_BKUP.forEach((user) => {
      distance = this.getNearCityUsers(
        user.latitude,
        user.longitude,
        this.cityLatitude,
        this.cityLongitude,
        this.userQuery
      );
      if (distance <= +this.userQuery) {
        this.locationAround = [...this.locationAround, user];
      }
    });

    this.allUsers = this.locationAround;
  }
}

<div class="app-portal" fxLayout="column" fxFlexFill>
  <p-panel header="DWP TASK">
    <p-dataView
      #selectedCity
      [value]="allUsers"
      [paginator]="true"
      [rows]="20"
      filterBy="last_name"
    >
      <ng-template class="headerBlock" pTemplate="header">
        <input
          class="cityName"
          type="search"
          [(ngModel)]="userQuery"
          (ngModelChange)="$userQuery.next($event)"
          pInputText
          style="margin-right: 15px"
          placeholder="Fetch user by City name or Miles - AUTO LOADS PAGE"
        />
        <input
          #userid
          class="cityName"
          type="search"
          [(ngModel)]="userID"
          pInputText
          placeholder="Enter userID and click Button"
          style="margin-right: 5px"
        />
        <button
          id="btnTest"
          *ngIf="userID"
          pButton
          type="button"
          class="p-button-raised p-button-rounded"
          label="User Details"
          (click)="getUserDetails(userid.value)"
        ></button>

        <div style="margin-top: 15px; display: flex; justify-content: flex-end;">
          <button
            id="btnTest"
            pButton
            type="button"
            class="p-button-raised p-button-rounded"
            label="Refresh Details"
            (click)="initialState()"
          ></button>
        </div>
      </ng-template>
      <ng-template let-user pTemplate="listItem">
        <div class="p-col-12 p-md-3">
          <div class="app-list">
            <div>
              <span style="font-weight: 600">user ID:</span> {{ user.id }}
            </div>
            <div><span>First Name:</span> {{ user.first_name }}</div>
            <div><span>Last Name:</span> {{ user.last_name }}</div>
            <div><span>Email:</span> {{ user.email }}</div>
          </div>
        </div>
      </ng-template>

      <ng-template let-item pTemplate="paginatordropdownitem">
        {{ item.value }} - per page
      </ng-template>
    </p-dataView>
  </p-panel>
</div>

// dwp-vue/src/components/PlayGround.vue
<template>
  <!-- Title of the page-->
  <div class="hello">
    <h1>{{ msg }}</h1>
  </div>

  <div>
    <div v-if="allUsers.length < 1">
      <label>No records found!<br /></label>
      <label
        >Your typed query is: {{ userQuery }}
        {{ isNumber() ? " Miles" : "city" }}</label
      >
    </div>

    <div class="userQueryArea">
      <div>
        <input
          v-if="allUsers.length > 1"
          class="cityName"
          type="search"
          name="userIDField"
          v-model="userQuery"
          placeholder="Enter City or Miles"
        />
        <button
          v-if="userQuery && allUsers.length > 1"
          id="userQueryValue"
          type="button"
          name="userBTN"
          :onclick="resolveQuery"
        >
          Fetch users
        </button>
      </div>
      <div>
        <input
          class="cityName"
          type="search"
          name="fetchUserDetails"
          v-model="userDetailsByID"
          placeholder="Enter userID to get more details"
        />
        <button
          type="button"
          name="userDetails"
          :onclick="fetchMoreUserDetails"
        >
          User Info
        </button>
      </div>
    </div>
  </div>

  <button
    style="float: right; margin-right: 10%"
    id="initialLoad"
    type="button"
    name="refresh"
    :onclick="initialState"
  >
    Refresh
  </button>

  <div id="main">
    <div
      v-for="user of allUsers"
      :key="user.id"
      :class="{
        colorExt: userDetailsByIDBtn,
      }"
    >
      <span
        v-if="userDetailsByID > 0 && userDetailsByIDBtn"
        class="textWeight"
        style="margin-right: 15px"
        >user ID: {{ user.id }}</span
      >
      <span v-if="userDetailsByID > 0 && userDetailsByIDBtn" class="textWeight"
        >City: {{ user.city }}</span
      >
      <br />
      <span class="textWeight">First Name:</span> {{ user.first_name }}<br />
      <span class="textWeight">Last Name:</span> {{ user.last_name }}<br />
      <span class="textWeight">Email:</span> {{ user.email }}<br />
      <span v-if="userDetailsByID > 0 && userDetailsByIDBtn" class="textWeight"
        >Latitude: {{ user.latitude }}</span
      >
      <br />
      <span v-if="userDetailsByID > 0 && userDetailsByIDBtn" class="textWeight"
        >Longitude: {{ user.longitude }}</span
      >
      <br />
      <span v-if="userDetailsByID > 0 && userDetailsByIDBtn" class="textWeight"
        >IP Address: {{ user.ip_address }}</span
      >
    </div>
  </div>
</template>

<script>
import axios from "axios";

export default {
  name: "PlayGround",
  data() {
    return {
      allUsers: [],
      userID: null,
      userQuery: null,
      fetchAllUsers_BKUP: [],
      locationAround: null,
      defaultCityName: "London",
      cityLatitude: 51.50722,
      cityLongitude: -0.1275,
      cityWiseUsersURL: "",
      userDetailsByID: null,
      userDetailsByIDBtn: false,
    };
  },
  props: {
    msg: String,
  },
  created() {
    this.getAllUsers();
  },
  methods: {
    getAllUsers() {
      axios
        .get("https://bpdts-test-app.herokuapp.com/users")
        .then((response) => {
          this.allUsers = response.data;
          this.fetchAllUsers_BKUP = response.data;
        });
    },
    getCityUsers() {
      this.setcityWiseUsers();

      axios.get(this.cityWiseUsersURL).then((response) => {
        console.log(">>", response.data);
        this.allUsers = response.data;
      });
    },
    resolveQuery() {
      if (this.isNumber()) {
        this.calculateDistance();
      } else {
        this.getCityUsers();
      }
    },
    calculateDistance() {
      let distance;
      this.locationAround = [];

      this.fetchAllUsers_BKUP.forEach((user) => {
        distance = this.getNearCityUsers(
          user.latitude,
          user.longitude,
          this.cityLatitude,
          this.cityLongitude,
          this.userQuery
        );
        if (distance <= this.userQuery) {
          this.locationAround = [...this.locationAround, user];
        }
      });
      this.allUsers = this.locationAround;
    },
    getNearCityUsers(
      eachLatitude,
      eachLongitude,
      cityLatitude,
      cityLongitude,
      unit
    ) {
      if (eachLatitude == cityLatitude && eachLongitude == cityLongitude) {
        return 0;
      } else {
        let radlat1 = (Math.PI * eachLatitude) / 180;
        let radlat2 = (Math.PI * cityLatitude) / 180;
        let theta = eachLongitude - cityLongitude;
        let radtheta = (Math.PI * theta) / 180;
        let distance =
          Math.sin(radlat1) * Math.sin(radlat2) +
          Math.cos(radlat1) * Math.cos(radlat2) * Math.cos(radtheta);

        if (distance > 1) distance = 1;

        distance = Math.acos(distance);
        distance = (distance * 180) / Math.PI;
        distance = distance * 60 * 1.1515;

        if (unit == "K") {
          distance = distance * 1.609344;
        }
        if (unit == "N") {
          distance = distance * 0.8684;
        }

        return distance;
      }
    },
    setcityWiseUsers() {
      this.cityWiseUsersURL = `https://bpdts-test-app.herokuapp.com/city/${this.userQuery}/users`;
    },
    initialState() {
      // RESET
      this.userQuery = null;
      this.userDetailsByID = null;
      this.userDetailsByIDBtn = false;
      this.allUsers = this.fetchAllUsers_BKUP;
    },
    isNumber() {
      return !isNaN(this.userQuery);
    },
    fetchMoreUserDetails() {
      if (this.userDetailsByID) {
        axios
          .get(
            `https://bpdts-test-app.herokuapp.com/user/${this.userDetailsByID}`
          )
          .then((response) => {
            this.userDetailsByIDBtn = true;
            this.allUsers = [response.data];
          });
      }
    },
  },
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#main {
  width: 100%;
  height: 100%;
  display: flex;
  flex-flow: row wrap;
  justify-content: center;
}

#main div {
  background-color: #ebe8e8;
  width: 24%;
  height: 100px;
  margin: 6px;
}

.textWeight {
  font-weight: 600;
}

.cityName {
  border: none;
  appearance: none;
  padding: 12px;
  border-radius: 5px;
  width: 250px;
  font-size: 14px;
  margin-right: 15px;
  border-bottom: 2px solid grey;
}

.hello {
  text-align: left;
}

.userQueryArea {
  display: flex;
  gap: 15px;
  justify-content: space-around;
}

button {
  background-color: #e4e4e4;
  color: black;
  padding: 10px 25px;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}

.colorExt {
  height: 200px !important;
}
</style>
